// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: render.proto

package render

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PB struct {
	Code                 int64      `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Now                  uint64     `protobuf:"varint,3,opt,name=Now,proto3" json:"Now,omitempty"`
	Data                 *types.Any `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PB) Reset()         { *m = PB{} }
func (m *PB) String() string { return proto.CompactTextString(m) }
func (*PB) ProtoMessage()    {}
func (*PB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9004acb5e772af, []int{0}
}
func (m *PB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PB.Unmarshal(m, b)
}
func (m *PB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PB.Marshal(b, m, deterministic)
}
func (m *PB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PB.Merge(m, src)
}
func (m *PB) XXX_Size() int {
	return xxx_messageInfo_PB.Size(m)
}
func (m *PB) XXX_DiscardUnknown() {
	xxx_messageInfo_PB.DiscardUnknown(m)
}

var xxx_messageInfo_PB proto.InternalMessageInfo

func (m *PB) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PB) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PB) GetNow() uint64 {
	if m != nil {
		return m.Now
	}
	return 0
}

func (m *PB) GetData() *types.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PB)(nil), "render.PB")
}

func init() { proto.RegisterFile("render.proto", fileDescriptor_ae9004acb5e772af) }

var fileDescriptor_ae9004acb5e772af = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0xcd, 0x4b,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0xa4, 0x24, 0xd3, 0xf3,
	0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0xa2, 0x49, 0xa5, 0x69, 0xfa, 0x89, 0x79, 0x95, 0x10, 0x25,
	0x4a, 0x79, 0x5c, 0x4c, 0x01, 0x4e, 0x42, 0x42, 0x5c, 0x2c, 0xce, 0xf9, 0x29, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x60, 0xb6, 0x90, 0x04, 0x17, 0xbb, 0x6f, 0x6a, 0x71, 0x71, 0x62,
	0x7a, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0x2b, 0x24, 0xc0, 0xc5, 0xec, 0x97,
	0x5f, 0x2e, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x12, 0x04, 0x62, 0x0a, 0x69, 0x70, 0xb1, 0xb8, 0x24,
	0x96, 0x24, 0x4a, 0xb0, 0x28, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xe8, 0x41, 0xec, 0xd3, 0x83, 0xd9,
	0xa7, 0xe7, 0x98, 0x57, 0x19, 0x04, 0x56, 0x91, 0xc4, 0x06, 0x16, 0x33, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xad, 0x8d, 0x9a, 0xce, 0xa9, 0x00, 0x00, 0x00,
}
